# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=512)),
                ('category_name', models.CharField(max_length=128)),
                ('subcategory_name', models.CharField(max_length=128)),
            ],
        ),
    ]
