# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(help_text=b'<strong>THE FILE UPLOADED MUST CONTAIN THESE THREE COLUMNS:<br/>1. Title<br/>2. Category ID<br/>3. Subcategory ID<br/>Plese note that the column names are case and space sensitive</strong>', upload_to=b'documents'),
        ),
    ]
